### PR TITLE
[#66] Set the new homepage and set block contents

### PR DESCRIPTION
**Pull request by juampynr**
We can't set block contents during site install because the
body field is not installed yet when dcamp_install() runs. Therefore,
I have updated README so it is now required to download the db
from Jenkins in order to install the site. This seems realistic to me
since now we have a production site so we need to work on database
updates from now on rather than installing a site.

## Testing steps

1. Download a copy of the production databse.
2. Install it.
3. Run database updates.
4. Open the homepage.

I see a couple bugs that we should work on follow ups though:

1. Block warnings during database updates:

```bash
juampy@Juampy/var/www/DCSpain/DrupalCampSpain/web(master)$ drush updb -y
The following module is missing from the file system: standard bootstrap.inc:236                                                           [warning]
The following updates are pending:

dcamp module : 
  8103 -   Add dummy sponsors for easy theming and default company logo. 
  8104 -   Add default blocks for frontpage. 
  8105 -   Sets the new theme and homepage. 

Do you wish to run all pending updates? (y/n): y
The following module is missing from the file system: standard bootstrap.inc:236                                                           [warning]
Performing dcamp_update_8103                                                                                                               [ok]
Performing dcamp_update_8104                                                                                                               [ok]
Performing dcamp_update_8105                                                                                                               [ok]
The block dcamp_2017_theme_breadcrumbs was assigned to the invalid region breadcrumb and has been disabled.                                [warning]
The block dcamp_2017_theme_help was assigned to the invalid region help and has been disabled.                                             [warning]
The block dcamp_2017_theme_messages was assigned to the invalid region messages and has been disabled.                                     [warning]
The block dcamp_base_theme_breadcrumbs was assigned to the invalid region breadcrumb and has been disabled.                                [warning]
The block dcamp_base_theme_help was assigned to the invalid region help and has been disabled.                                             [warning]
The block dcamp_base_theme_messages was assigned to the invalid region messages and has been disabled.                                     [warning]
Cache rebuild complete.                                                                                                                    [ok]
Finished performing updates.                                                      
```

2. Warning at Admin > Config:

image

### CODE REVIEW

**Comment by juampynr** [comment]
cc @nuez @ckrina @samuelsolis

**Comment by nuez** [comment]
As a workaround I'm ok with it,

As a definite solution I'm not so sure about this:

- We would basically make it impossible to contribute for anyone without access to jenkins.
- The website would stop being a blueprint for future development.

Which module installs the field_body? Can't we add it as dependency to the module?

**Comment by juampynr** [comment]
> We would basically make it impossible to contribute for anyone without access to jenkins.

They can still install the site and get a basic setup (I have updated the config files). As we progress, having a copy of the production site becomes more important, right? Otherwise you are not working on top of real data.

> The website would stop being a blueprint for future versions of Dcamp.

Hmm, I don't follow you here. Are you talking about being able to reuse this in future camps? I am not that concerned about this, given how we are doing with deadlines. Is this something we can fix afterwards?

> generally, as soon as you start working with dumps, you introduce corruption.

What do you suggest to do instead?

> Which module installs the field_body? Can't we add it as dependency to the module?

I tried: we need block_content and text modules as dependencies of dcamp. However, by the time dcamp_install runs, the body field of the block content entity is not present yet. We may need to move this logic to config_installer.profile.

**Comment by nuez** [comment]
I've done a bit of testing and I can't really see another option than the one you suggested: 

A couple of things:

- You don't need to change the landing page theme. (doing so will break the design of the landing theme)
- I think that in the instructions we can have both options: either donwload the dump, or install by importing configuration. In case of the latter, users would have to execute "drush ev _dcamp_add_content_blocks_for_frontpage()" and then drush cim sync,  to install the default blocks.

**Comment by samuelsolis** [comment]
Where can I find a dump to download the production database? I want to test this issue and the others PR in order to deploy both asap and close the 1.0 milestone.

Thanks and good job guys!

**Comment by juampynr** [comment]
Done. Merging.

**Pull request merged**
