### PR TITLE
[#67] Add speaker content type and view block

### PR DESCRIPTION
**Pull request by juampynr**
Includes the content type and the block view to be used at the new home.

### CODE REVIEW

**Comment by juampynr** [comment]
@samuelsolis, @nuez, please have a look.

**Comment by nuez** [comment]
I'm not sure if we need all the social media fields, but according to the design we're missing

- bitbucket
- facebook
- github
- drupal.org

We also need the twitter nick (or should it be the drupal.org nick) for the teaser. (or is that the twitter field?)

I think drupal.org is important to have as social media link.

The images for teaser and full are different: Check with WWW if the background is going to be added in CSS or not, (would be the best), in which case 1 image field will do, but it would be good to add image styles that match the sizes of the design.

I would also already put the right fields in the view modes, remove the labels, etc.

The view: I would prefer not to have 'views' fields but render the teaser of the node instead.

**Comment by nuez** [comment]
If I can  be really picky ;): change the machine name of the view: not block_1 but just block.

**Comment by juampynr** [comment]
> I'm not sure if we need all the social media fields, but according to the design we're missing
> 
> bitbucket
> facebook
> github
> drupal.org

Added.

> We also need the twitter nick (or should it be the drupal.org nick) for the teaser. (or is that the twitter field?)

The teasers use the Twitter account.

> I think drupal.org is important to have as social media link.

Yep, added.

> The images for teaser and full are different: Check with WWW if the background is going to be added in CSS or not, (would be the best), in which case 1 image field will do, but it would be good to add image styles that match the sizes of the design.

cc @wildwildweb

> I would also already put the right fields in the view modes, remove the labels, etc.

Done.

> The view: I would prefer not to have 'views' fields but render the teaser of the node instead.

Done.

> If I can be really picky ;): change the machine name of the view: not block_1 but just block.

Done

**Comment by juampynr** [comment]
@nuez, can you review again?

**Comment by wildwildweb** [comment]
Hi guys, Speakers images will be transparent pngs (Iván Redondo will take care of these).
So we have:
**Teaser:**+ grey background for the img element
**Node:** grey background color and pattern background starting in the middle.
Let me know if you need help with the css here.

**Comment by nuez** [comment]
Thanks @wildwildweb So we just need 1 image field. It would be good to add a default image (to make theming easier, and in case we don't have the image yet). I don't know how d8 saves the default image, and can it be added to the repo. D7 saved it to public:// or private:// so it was no use, if D8 allows you to use a default image that can be added to the repo, it would be good to add one.

**Comment by juampynr** [comment]
Yes, we can save a default image. @wildwildweb, please let us know when you have it.

**Pull request merged**
