### PR TITLE
Translate articles and blocks

### PR DESCRIPTION
**Pull request by juampynr**
@nuez @samuelsolis this adds support to translate articles and content blocks. We need this in Prod in order to translate these. I have tested it locally so, if you agree, please merge and I will make a new release and deploy to Prod.

### CODE REVIEW

**Comment by nuez** [comment]
@juampynr OK, only doubt I have is if we need the comments or not? I will merge this anyway

**Comment by juampynr** [comment]
No, we don't have comments in the site, but Drupal exports the config anyway.

**Comment by nuez** [comment]
Maybe uninstall the comment module? Then it shouldn't add it. I think I've done this before but it must have merged and got back in somewhere.

**Comment by juampynr** [comment]
@nuez that sounds good to me!

**Pull request merged**
