### PR TITLE
#146 Added Hamburguer menu animation

### PR DESCRIPTION
**Pull request by ckrina**

### CODE REVIEW

**Comment by juampynr** [comment]
:hamburger:

**Comment by juampynr** [comment]
@ckrina when I checkout this PR, I can only see the hamburguer icon when being logged out. Can you have a look?

**Comment by isholgueras** [comment]
I can take a look later today. And I also have to fix the icon's size.

**Comment by ckrina** [comment]
Here's how it looks.
dcamp-hamburguer

**Pull request merged**
