### PR TITLE
[#7] Add language switcher to the header

### PR DESCRIPTION
**Pull request by juampynr**
Also, save config files along with the tar.gz in order to be able to diff them in future pull requests. I am also taking the chance to add the exported config files, so we can see differences in future pull requests.

Here is the language switcher after installing the site with this pull request:

selection_001

Currently, the Maichimp sign-up form is configured as a page instead of a block. Is this okay or should it be a block attached to a node? I am wondering what is easier to theme and easier to translate. cc @nuez @ckrina:

selection_002

### CODE REVIEW

**Comment by juampynr** [comment]
Even though this is a bit out of scope for this PR, it is related since I decided to add the config files: I have updated the README so it explains the contributing worklow: https://github.com/juampynr/DrupalCampSpain/pull/9/commits/83458166560dbb945a4f41246755f26634494bb4

**Comment by nuez** [comment]
@juampynr definitely good idea to include the config files for diff review. 

About the mailchimp: Better as a block. Whether or not it should be attached to a node, would depend on the approach:

- Create a content type for the landing page, to be able to create future landing pages easily.
- Or not use a content type for the landing page, instead a custom twig file with regions and blocks specific to the landing page.

If we're only going to build one landing page per installation, I don't like the idea to have a specific node type for that, and I prefer to just render the blocks in regions.

However if we're going to keep using the same installation for future Drupalcamp websites, and create different landing pages that are always going to follow the same pattern, a node type would make sense.

**Comment by nuez** [comment]
A block is an entity, so either would be easy to translate in D8, i assume at least:)

**Comment by ckrina** [comment]
@juampynr I guess when it appears it won't be the main element in the page, so I bet for something similar to a independent block/component.

**Comment by nuez** [comment]
I think this can be merged, but i don't have the permissions to do so.

**Comment by juampynr** [comment]
Closing in favor to https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/10

**Comment by juampynr** [comment]
@nuez, do you think that this is still valid? It may be easier to create a new PR.

**Comment by nuez** [comment]
Well, I think mainly for the configuration files, not for the block, it would still be valid but it wouldnt be strictly necessary. Mainly to see diff in the configuration.

**Pull request closed without merging**
