### PR TITLE
[#67] Featured speakers theming

### PR DESCRIPTION
**Pull request by ckrina**
Added theming for the speakers content type.
Also added a responsive image style for the big top image.

The theming and the responsive imgage styles can be reused for other content types because part of the styles are content-type agnostic (node__title, node__body, etc).

Very basic layout styles have been added, it would be good to improve it with more time.

### CODE REVIEW

**Comment by nuez** [comment]
Good work, couple of things:
image


-  The image on the teaser is squashed
- The image on the full node requires a specific format. That's fine, but it would be good to know what it is and force dimensions through UI.
- The title of the node on the teaser should be removed on the frontpage. (see image)
- I think it's a bit unnecessary to have the 'full name' field. Why don't we just use the title field?
- I spoke to @wildwildweb and I believe the idea is that they will give us the cut-out png images of the speakers. We will have to add the background to it with CSS (half of the full node bg with stripes). 
- Add default image: See image:
default-image

**Comment by ckrina** [comment]
- I just addressed the node detail/full theming, not the teaser/home one.
- I don't follow you with the full node image and forcing dimensions.
- I agree with the redundancy of using the full name field.
- We should consider adding LinkedIn as a field.
- Is there any default image? If yes, where is it?

**Comment by juampynr** [comment]
I am okay with merging this and work on the remaining items in follow ups. These being (correct me if I am wrong):

1. Removing the full name field.
2. Theming the teaser.
3. Adding a LinkedIn link.

@nuez, if you are okay with the above, please go ahead and merge this.

**Comment by nuez** [comment]
Looking good, @juampynr can you create issues for the remaining tasks?

**Comment by nuez** [comment]
See #87

**Comment by juampynr** [comment]
@nuez, @ckrina: I have created https://github.com/AsociacionDrupalES/DrupalCampSpain/pull/92, which removes a reference to the full name field and adds the LinkedIn field.

**Pull request merged**
