### PR TITLE
[#83] Add LinkedIn field and remove full_name

### PR DESCRIPTION
**Pull request by juampynr**
@nuez, @ckrina, feel free to take over this PR and add the theming for the teaser, or just merge it and create a new PR for it.

### CODE REVIEW

**Comment by nuez** [comment]
Full name has been removed already

**Comment by nuez** [comment]
Sorry thought this was an issue (on mobile phone)

**Comment by nuez** [comment]
Please revise the display settings, currently it shows the label. Check teaser and full.

**Comment by juampynr** [comment]
Weird, I could not find it when I searched for it. Will do later.

**Comment by juampynr** [comment]
@nuez, done. I also added a db update to create featured speaker nodes.

**Comment by juampynr** [comment]
image

**Comment by nuez** [comment]
The reason why I added the promoted filter on the view is: when we have more than 3 speakers, we need to be able to select which ones go on the frontpage.

**Comment by juampynr** [comment]
We won't have more.

**Comment by juampynr** [comment]
Okay, maybe we will, but at this time is highly unlikely.

**Pull request merged**
