### PR TITLE
199. Added highlighted image for page content type

### PR DESCRIPTION
**Pull request by isholgueras**
And also added block for display image in node

### CODE REVIEW

**Comment by juampynr** [comment]
@isholgueras, before I merge this: why do we need a view to show this header image? Can't we print it in the template?

image

**Comment by isholgueras** [comment]
@juampynr I made a view and a block because there is no template for this content type and because I'm reusing the field_image from the article. If we want to add the same field_image to other content types, we only need to add this field.

And the other reason is because view gives the widget options and is very quick to implement it.

I can try to modify the template if you think is needed

**Comment by wildwildweb** [comment]
@isholgueras @juampynr thanks guys!! Can i upload the images now?

**Comment by isholgueras** [comment]
I'm going to push a new PR with that fix.

**Pull request closed without merging**
