### PR TITLE
New 2018 theme

### LINKED ISSUE #308: Create 2018 theme
We now have the 2018's landing theme. It's time to create the 2018's full theme that includes a menu as we did for 2017's DrupalCamp.

The first challenge that I see is that we have 5 active themes now:

image

I think that we need to:

* Figure out which themes we need from that list. Disable the rest.
* Create a dcamp_2018_theme using dcamp_2017 as a foundation.

@nuez, can you help us on this? I will do some tinkering to see if I can figure something out. @ferelx feel free to do it if you know about this stuff.

### PR DESCRIPTION
**Pull request by nuez**
2018 base theme created. 

Closes #308

### CODE REVIEW

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr312-vwwnwnx8dgkw0kaljneekdtw9fpike0r.tugboat.qa

**Comment by nuez** [comment]
Looking great that Tugboat! Thanks for that @juampynr. 

Looks like i broke the landingpage. 

BTW we now compile CSS by using the 2017 theme's CSS so we don't copy CSS and keep the code DRY. (could be DRYer though)

**Comment by nuez** [comment]
Fixed the missing libraries that caused the Tugboat preview to break.

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr312-vwwnwnx8dgkw0kaljneekdtw9fpike0r.tugboat.qa

**Comment by nuez** [comment]
Also closes #313

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr312-vwwnwnx8dgkw0kaljneekdtw9fpike0r.tugboat.qa

**Pull request merged**
