### PR TITLE
#84: Added collaborators sponsor type.

### PR DESCRIPTION
**Pull request by samuelsolis**
#84 I added collaborators as new sponsor type. I added a new block display in the sponsor view that only list the collaborators elements (I'm not sure if it is a required block but maybe can be useful).

### CODE REVIEW

**Comment by nuez** [comment]
Just a question, the design includes a section for individual sponsors too maybe we should include that too in this pull request?

**Comment by samuelsolis** [comment]
Yes, @nuez. We forgot the individual sponsors, and... we have to open any way to be an individual sponsor too. Maybe when users buy the ticket. 

Individual sponsors can be another sponsor type but the image style have to be different and in, the design, the individual sponsor have an extra field too (Name + Nick). With this things in mind I'm not sure if use the same content type is an advantage or an inconvenience.

What do you think? Maybe we can use the same content type but exclude this type in the "All sponsor" view view block, using a new block  (with this own style) instead. It can be a problem for theming?

**Comment by juampynr** [comment]
I am thinking about pulling attendees (including individual sponsors) from the EventBrite API directly into a Drupal template, relying in Cache API for performance. Therefore, I don't think that we will need a content type for Individual Sponsors. If I see any blockers when we reach to that point, then I am okay about importing this data into a content type.

How does that sound?

**Comment by nuez** [comment]
Sounds like a good idea.. and fun to build. The design shows the individual sponsors as just another sponsor type, with photos. Not sure if event brite allows you to upload and pull the image. That would be my only concern

**Comment by samuelsolis** [comment]
Yeah! I like this idea, we can create a new issue for the individual sponsor task.

**Pull request merged**
