### PR TITLE
Refactoring SCSS

### PR DESCRIPTION
**Pull request by nuez**
This PR seeks to refactor SCSS and solve a pending issue: the blue bullet for navigation (used to be pink).

It implements Sass globbling (to automagically add .scss files in subfolders, instead of having to declare them in the main SCSS file individually)

The blue is slightly darker than defined in the variable, not to disappear against the blue background of one of the sections on the landing page.

#40 #42

### CODE REVIEW

**Comment by juampynr** [comment]
@nuez, how can I test this locally?

**Comment by nuez** [comment]
Pull and see if everything looks and works the same apart from:

the bullets which should look now like the ones suggested in #42

**Comment by juampynr** [comment]
Do I need to run a command such as gulp to compile the SASS?

**Comment by nuez** [comment]
The compiled  CSS is included in the branch, so it shouldn't be necessary to compile. But if you want just for checking you can recompile it, (it should get you the exact same result).

How to run gulp, you would need to install node and npm, go to the folder with the theme and run 'npm install'. After that gulp should fire up everything. Hope that works for you, let me know if it doesn't.

As in the instructions in readme.txt

- Go to web/themes/dcamp_base_theme
- Run 'npm install' (you might need to install node/npm first)
- Install LiveReload for chrome (https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei?hl=en)
- Run 'gulp' in the terminal
- Activate LiveReload in chrome
- Happy styling!

**Pull request merged**
