### PR TITLE
Set the homepage to the full theme

### PR DESCRIPTION
**Pull request by juampynr**
* Remove thank you from splash image at top.
* Add call for papers.
* Remove unused blocks.
* Listing featured speakers.

### CODE REVIEW

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
Phew, I am making a mess of this. See: this is what I have locally:

image

I don't know what is the best practice for structuring landing pages. See. This is the block layout for dcamp_2018_landing_theme:
image

And here is the one for dcamp_2018_theme:

image


As you can see, the former has custom blocks with text and then the theme adds all the styling, while for the latter we have everything in the frontpage template (see this pull request's diff).

Ideally, we should have a set of blocks that we can pull in and out depending on which phase of the camp we are at. Here is a suggested list:

- splash
- drupal + counter
- venue
- join aed
- newsletter- splash
- drupal + counter
- venue
- join aed
- newsletter
- footer

- featured speakers
- call4papers
- sponsors
- become a sponsor

- view selected sessions
- view schedule
- footer
- featured speakers
- call4papers
- sponsors
- become a sponsor
- view selected sessions
- view schedule

Can't we have the above as individual blocks? Then, we could assign them to the front page as we need them.

@nuez @ferelx I need your feedback in this as I am stuck.

**Comment by nuez** [comment]
I agree this could be easier, but I think there is some confusion here:

The frontpage in the image is dcamp_2018_theme + frontpage.twig.html + DcampController:frontpage().

It doesn't have anything to do with the dcamp_2018_landing_theme.

We could refactor this so it uses blocks, but that would require quite some refactoring. Please let me know what you want to do here.

**Comment by juampynr** [comment]
Here is how the full theme looks like:

image

And here is the menu expanded:

image

@ferelx, all yours!

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by ignaciolflores** [comment]
FYI, this is how I see the page using Firefox 58 in a 2K monitor.
image

**Comment by juampynr** [comment]
@ferelx has, unfortunately, some work to do. I am useless in this matter. :neckbeard:

**Comment by juampynr** [comment]
@ferelx pages like the ones for speakers or camp content need some adjustments too. See this:

https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa/es/pages/guia-de-supervivencia
image


https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa/es/speakers/laura-bonmati
image

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Comment by juampynr** [comment]
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Links:
- https://pr317-2lsfv7sxyj7l2v911zs7sgsgykgyduvj.tugboat.qa

**Pull request merged**
